#!/usr/bin/env python3
"""Terrain raster for the route plates: app/public/map/terrain.bin (2 x uint16 LE per texel, row 0 =
north) with R = elevation (0 = 700 m, 65535 = 4100 m, clipped) and G = water mask (Lake Sevan), plus map.json
(bounding box, size, place positions in 0..1 map coordinates).

Usage: python3 make_map.py <map_dir with heights.npy, sat.jpg, meta.json> <repo_root>
"""
import json, os, sys
import cv2
import numpy as np

SRC, ROOT = sys.argv[1], sys.argv[2]
OUT = os.path.join(ROOT, "app", "public", "map")
os.makedirs(OUT, exist_ok=True)
meta = json.load(open(os.path.join(SRC, "meta.json")))
h = np.load(os.path.join(SRC, "heights.npy"))
sat = cv2.imread(os.path.join(SRC, "sat.jpg"))
LON0, LON1, LAT0, LAT1 = 44.30, 45.50, 39.90, 40.80   # crop (portrait-ish after cos(lat) scaling)
N = 1024
def crop(img):
    rows, cols = img.shape[:2]
    c0 = int((LON0 - meta["lon0"]) / (meta["lon1"] - meta["lon0"]) * cols)
    c1 = int((LON1 - meta["lon0"]) / (meta["lon1"] - meta["lon0"]) * cols)
    r0 = int((meta["lat1"] - LAT1) / (meta["lat1"] - meta["lat0"]) * rows)
    r1 = int((meta["lat1"] - LAT0) / (meta["lat1"] - meta["lat0"]) * rows)
    return img[r0:r1, c0:c1]
hc = cv2.resize(crop(h), (N, N), interpolation=cv2.INTER_AREA)
sc = cv2.resize(crop(sat), (N, N), interpolation=cv2.INTER_AREA)
hsv = cv2.cvtColor(sc, cv2.COLOR_BGR2HSV)
water = ((hsv[..., 2] < 70) & (np.abs(hc - 1900) < 25)).astype(np.uint8) * 255
water = cv2.morphologyEx(water, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
n, lab, stats, _ = cv2.connectedComponentsWithStats(water)
if n > 1:
    big = 1 + np.argmax(stats[1:, cv2.CC_STAT_AREA]); water = (lab == big).astype(np.uint8) * 255
water = cv2.GaussianBlur(water, (0, 0), 1.2).astype(np.float32) / 255
# 16 bits per channel: 8-bit elevation (13 m steps) terraces the 50 m contours at close zoom
elev = np.clip((hc - 700) / 3400, 0, 1)
np.round(np.dstack([elev, water]) * 65535).astype("<u2").tofile(os.path.join(OUT, "terrain.bin"))
PLACES = {"yerevan": (40.1776, 44.5126), "garni": (40.1125, 44.7302), "geghard": (40.1403, 44.8183),
          "sevan": (40.558, 45.004), "sevanavank": (40.5645, 45.0125)}
pos = {k: [(lon - LON0) / (LON1 - LON0), (LAT1 - lat) / (LAT1 - LAT0)] for k, (lat, lon) in PLACES.items()}
km_x = (LON1 - LON0) * 111.32 * np.cos(np.radians((LAT0 + LAT1) / 2)); km_y = (LAT1 - LAT0) * 110.57
json.dump({"n": N, "bbox": [LON0, LAT0, LON1, LAT1], "km": [round(km_x, 2), round(km_y, 2)],
           "elev": [700, 4100], "places": pos}, open(os.path.join(OUT, "map.json"), "w"), indent=1)
print("map", N, "km", km_x, km_y, "water px", int((water > 0.5).sum()))

# Lake Sevan's whole shoreline (the crop above cuts its eastern end) for the lake inset on the Sevan
# plate: app/src/scenes/_lake.ts, the outline in km-true proportions fitted to a 0.9 x 1 box (y down).
rows, cols = h.shape
hsv_full = cv2.cvtColor(cv2.resize(sat, (cols, rows), interpolation=cv2.INTER_AREA), cv2.COLOR_BGR2HSV)
lake = ((hsv_full[..., 2] < 70) & (np.abs(h - 1900) < 25)).astype(np.uint8) * 255
lake = cv2.morphologyEx(lake, cv2.MORPH_OPEN, np.ones((5, 5), np.uint8))
lake = cv2.morphologyEx(lake, cv2.MORPH_CLOSE, np.ones((9, 9), np.uint8))
n, lab, stats, _ = cv2.connectedComponentsWithStats(lake)
lake = (lab == 1 + np.argmax(stats[1:, cv2.CC_STAT_AREA])).astype(np.uint8) * 255
cs, _ = cv2.findContours(lake, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
cnt = max(cs, key=cv2.contourArea)
cnt = cv2.approxPolyDP(cnt, 1.2, True)[:, 0, :].astype(float)
kx = (meta["lon1"] - meta["lon0"]) * 111.32 * np.cos(np.radians(40.4)) / cols
ky = (meta["lat1"] - meta["lat0"]) * 110.57 / rows
xk, yk = cnt[:, 0] * kx, cnt[:, 1] * ky
xk, yk = xk - xk.min(), yk - yk.min()
s = min(0.9 / xk.max(), 1.0 / yk.max())
pts = [[round(a * s, 4), round(b * s, 4)] for a, b in zip(xk, yk)]
pts.append(pts[0])
with open(os.path.join(ROOT, "app", "src", "scenes", "_lake.ts"), "w") as f:
    f.write("// Lake Sevan's shoreline (generated by analysis/make_map.py): km-true proportions, fitted to a\n"
            "// 0.9 x 1 box, y down, closed. %.1f km across at 1 unit.\n" % (1 / s))
    f.write("export const LAKE_KM = %.2f;\n" % (1 / s))
    f.write("export const LAKE: [number, number][] = %s;\n" % json.dumps(pts, separators=(",", ":")))
print("lake outline", len(pts), "points, km per unit", 1 / s)
